language: node_js

node_js:
  - '10'
  - '8'

branches:
  except:
    - /^v[0-9]/

before_install:
  - echo "//npm.dvhb.io/:_authToken=\${NPM_TOKEN}" >> .npmrc

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npx semantic-release
